version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
